### ISSUE TITLE
Lean component vs Smart/container component vs dumb/presentational component

### ISSUE THREAD

**Issue by mslawins** [Yonet/Angular2-Interview-Questions#27]
Hey Yonet,

there are two separate questions which I have problem to reason about:

##### What does a lean component mean to you?

and

##### What is the difference between a smart/container component and dumb/presentational component? What is a good use case example? What are the advantages?

This is my answer to the first one based on documentation:

A lean component is a component which solely purpose is to display data to user. This means such component delegates data fetching, business logic, input validation etc. to other classes like models, services, redux effects/actions etc. Lean component follows single responsibility principle.

This is my current understanding of the second one:

* dump/presentational component only displays data, data is transferred into this component only via @Input() decorator, preferably this data is immutable or observable which together with OnPush change detection allows for performance optimisation, this means that such component does not have any conditionals or loops and it is lean by definition
* smart/container - this component handles conditionals and loops,  this component could be called lean if it delegates data fetching and business logic (or not if handles it directly)

Could you please fix my way of thinking if I am wrong?

**Comment by Yonet** [comment]
@mslawins you are correct in your answers. Please add them to the related readme and be a contributor. Thanks!

**Comment by LayZeeDK** [comment]
[I agree](https://blog.angularindepth.com/lean-angular-components-252bcb6ea6c1)
